title: andrewhil.es
description: Personal website for Andrew Hiles - Developer from Belfast.

name: Posts
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
comments: true
baseurl:

plugins:
  - jekyll-feed

timezone: Europe/London

exclude:
  - package.json
  - node_modules
  - gulpfile.js

# Google Analytics
google_analytics: UA-142621470-1
